name: CI
on: [push, pull_request]

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get install -y g++

      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.14
        with:
          cmake-version: "3.25"

      - name: Configure CMake
        run: cmake -B build -S . -DBUILD_TESTING=ON -DBUILD_DOCS=OFF

      - name: Build
        run: cmake --build build

      - name: Install
        run: sudo cmake --install build

      - name: Test
        run: ctest --test-dir build --output-on-failure
  docs:
    needs: build-and-test
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get install -y g++ doxygen

      - uses: actions/setup-python@v4

      - name: Install python dependencies
        run: python -m pip install sphinx sphinx-rtd-theme sphinx-sitemap breathe

      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.14
        with:
          cmake-version: "3.25"

      - name: Configure CMake
        run: cmake -B build -S . -DBUILD_DOCS=ON -DBUILD_TESTING=OFF

      - name: Build
        run: cmake --build build

      - name: Setup pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: "docs/_build/html/"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
  release:
    if: ${{ github.ref == 'refs/heads/main' }}
    permissions:
      contents: write
      pull-requests: write
    needs:
      - docs
      - build-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4
        with:
          release-type: simple
          package-name: qualpal
          config-file: release-please-config.json
