name: Code-coverage

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  code-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Install dependencies
        run: |
          sudo apt-get install -y \
            build-essential \
            lcov \
            gcovr \
            catch2

      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v2.0
        with:
          cmake-version: "3.25"

      - name: Configure CMake with Coverage
        run: cmake -B build -S . -DBUILD_TESTING=ON -DENABLE_COVERAGE=ON -DBUILD_CLI=ON

      - name: Build with Coverage
        run: cmake --build build

      - name: Run tests for coverage
        run: ctest --test-dir build --output-on-failure

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5.5.1
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
